In [1]:
#import numpy package
import numpy as np

In [4]:
#create a empty array
arr=np.array([])
print (arr)
print(type(arr))

['vishwa' '23' '12.3']
<class 'numpy.ndarray'>


In [6]:
#create  numpy array to store values  such as 8,5,8,7,4,5,6,9
arr1=np.array([8,5,8,7,4,5,6,9])
print(arr1)
print(type(arr1))

[8 5 8 7 4 5 6 9]
<class 'numpy.ndarray'>


In [10]:
#create numpy array to store values such blue,green,orange,yellow,white
arr2=np.array(("blue","green","orange","yellow","white"))
print(arr2)
print(type(arr2))

['blue' 'green' 'orange' 'yellow' 'white']
<class 'numpy.ndarray'>


In [6]:
#how to create an array using list
import numpy as  np
List=[24,45,67,78,54,32,45]
arr=np.array(List)
print(arr)
print(type(arr))

[24 45 67 78 54 32 45]
<class 'numpy.ndarray'>


In [7]:
tuple=(101,102,103,104,105,106,108)
arr=np.array(tuple)
print(arr)
print(type(arr))

[101 102 103 104 105 106 108]
<class 'numpy.ndarray'>


**1-D array**

In [14]:
arr=np.array([1,2,3,4,5,6])
print(arr)
print("dimension of array is",arr.ndim)
print("number of elements is",arr.size)
print("data type of elements in an array",arr.dtype)

[1 2 3 4 5 6]
dimension of array is 1
number of elements is 6
data type of elements in an array int64


In [20]:
# 2-D array
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [30]:
arr_2d=np.array([[4,5,6,7],[5,2,9,7],[1,3,2,8,],[4,3,5,6,]])
print(arr_2d)
print("dimension",arr_2d.ndim)
print("no of elements",arr_2d.size) 
print("order of matrix",arr_2d.shape)

[[4 5 6 7]
 [5 2 9 7]
 [1 3 2 8]
 [4 3 5 6]]
dimension 2
no of elements 16
order of matrix (4, 4)


**3-D array**

In [36]:
arr_3d=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr_3d)
print(arr_3d.ndim)
print("shape",arr_3d.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3
shape (1, 3, 3)


**4-D array**

In [7]:
import numpy as np
arr_4d=np.array([[[[1,2,2,1],[3,4,3,4],[5,6,5,6],[7,8,7,8]]]])
print(arr_4d)
print(arr_4d.ndim)
print("shape",arr_4d.shape)

[[[[1 2 2 1]
   [3 4 3 4]
   [5 6 5 6]]]]
4
shape (1, 1, 3, 4)


**built-in function to generate a numpy array**


In [ ]:
#arange: it is used to generate evenly spaced values within a given interval
note:end value is not included

In [5]:
#generate values from 0 to 14
import numpy as np
np.arange(15)       #end value is not included

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
#generate the values from 0 to 20
np.arange(21)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [13]:
#generate values from 101 to 115
#we use arange(start,end)
np.arange(101 , 116)

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
       114, 115])

In [14]:
#generate values from 400 to 480
np.arange(400,481)

array([400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412,
       413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425,
       426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438,
       439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451,
       452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464,
       465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477,
       478, 479, 480])

In [16]:
#generate values from -400 to -350
np.arange(-400,-349)

array([-400, -399, -398, -397, -396, -395, -394, -393, -392, -391, -390,
       -389, -388, -387, -386, -385, -384, -383, -382, -381, -380, -379,
       -378, -377, -376, -375, -374, -373, -372, -371, -370, -369, -368,
       -367, -366, -365, -364, -363, -362, -361, -360, -359, -358, -357,
       -356, -355, -354, -353, -352, -351, -350])

In [19]:
#generate first 10 even numbers
#arange(start,end,step) it means you give starting points and end points and u also give how much step you are giving for eg.
np.arange(0,21,2)


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [20]:
np.arange(2,21,2)


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [23]:
#generate an array which include 10 multiple of 5
np.arange(5,51,5)   #note:this is also same thing we start,end and step

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [25]:
np.arange(6,61,6)

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54, 60])

In [13]:
#multiple 10 of 8
np.arange(8,81,8,)

array([ 8, 16, 24, 32, 40, 48, 56, 64, 72, 80])

**ones**

In [27]:
#ones:returns on array with all ones


In [32]:
#it return 1-D array with as 1
np.ones(4)    #note:you see the output it will print with dot(.) beacuase floating point numbers

array([1., 1., 1., 1.])

In [33]:
#how to print integer like without dot symbol eg.
np.ones(5, dtype=int)


array([1, 1, 1, 1, 1])

In [35]:
#return 1-D array 10 elements as 1
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [36]:
#create a unit matrix of order (2,2)
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [37]:
#create a unit matrix of order (5,3)
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [39]:
#create a unit matrix of order (4,4)
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

**zeros**

In [40]:
#create a 1-D array with 5 elements as 0
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [42]:
#create a 2-D array of order(3,3)
np.zeros((3,3))               #note:2-d array we have to use 2 brackets

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [43]:
#create a 3-D array of order(5,3)
np.zeros(((5,3)))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

**eye--identity**

In [44]:
#create (2,2)identity matrix
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [45]:
#create (3,3)identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
#create (4,3)identity matrix
np.eye(4,3)     #note you eneterd both 4 only or 4,3 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

**full--- it is used generate with same elements**

In [3]:
#create (2,2)with all elements as 10
import numpy as np
np.full((2,2),10)

array([[10, 10],
       [10, 10]])

In [2]:
#create (4,3)with all elements as 20
import numpy as np
np.full((4,3),20)

array([[20, 20, 20],
       [20, 20, 20],
       [20, 20, 20],
       [20, 20, 20]])

**linspace--it is used to generate linear spaced values**

In [5]:
#generate linear spaced vlues between 1 to 5
np.linspace(1,5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [8]:
#generate 10 equally spaced values between 1 to 100
np.linspace(1,100,num=10,retstep=True)    #note:retstep is used difference between elements like 1 to 12 is diference=11

(array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.]),
 np.float64(11.0))

In [7]:
#generate 10  numbers between 1 to 1000 and find the differenc
np.linspace(1,1000,num=10,retstep=True)

(array([   1.,  112.,  223.,  334.,  445.,  556.,  667.,  778.,  889.,
        1000.]),
 np.float64(111.0))