**Random**

**randint**

In [5]:
#create an array with includes 10 random integers between 1 to 100
#randint:-it is used to generaterandom integers for given interval
import numpy as np
np.random.randint(1,100,10)

array([ 5, 72, 89, 38, 96, 60, 58, 97, 81,  5], dtype=int32)

In [7]:
#generate an array which includes 5 random values between 1 to 1000
np.random.randint(1,1000,5)

array([777, 341, 268, 927, 870], dtype=int32)

In [9]:
#create a 2-D array of order(2,2) which includes random integers between 20 to 60
np.random.randint(20,60,size=(2,2))

array([[42, 40],
       [34, 40]], dtype=int32)

In [11]:
#create a 2-D array of order(2,3) which includes random integers between 2 to 200
np.random.randint(2,200,size=(2,3))

array([[196, 117,  86],
       [ 50, 125,  34]], dtype=int32)

**rand**

In [17]:
#generate  10 random numbers between(0,1)
np.random.rand(10)

array([0.44485843, 0.74168703, 0.52664231, 0.42205985, 0.11630938,
       0.68222094, 0.50235515, 0.66178927, 0.38623969, 0.45681593])

In [18]:
np.random.rand(100)

array([0.74274627, 0.6821631 , 0.04716548, 0.61840787, 0.09381893,
       0.57624941, 0.95450508, 0.39624603, 0.30493897, 0.04844918,
       0.43275033, 0.45565188, 0.44335729, 0.37740866, 0.5078888 ,
       0.30890228, 0.03141354, 0.94965742, 0.3405721 , 0.33703682,
       0.48585537, 0.3707986 , 0.03295452, 0.75934836, 0.00769908,
       0.75271835, 0.95225584, 0.18395798, 0.49111219, 0.80922609,
       0.0118846 , 0.28741793, 0.69130853, 0.51718782, 0.57604228,
       0.80272592, 0.43961306, 0.64229291, 0.47883773, 0.68467174,
       0.05325818, 0.97262836, 0.00378156, 0.3936796 , 0.7627191 ,
       0.40105238, 0.57662696, 0.53776587, 0.31812967, 0.83159414,
       0.73907431, 0.39164478, 0.2920509 , 0.1025459 , 0.44988987,
       0.50872464, 0.25968016, 0.30629102, 0.63977327, 0.89986749,
       0.1577863 , 0.63009997, 0.38355701, 0.85138345, 0.25973578,
       0.78159763, 0.28648685, 0.88868857, 0.58049841, 0.56392338,
       0.13008026, 0.33011408, 0.05238611, 0.44603378, 0.03367

In [3]:
#create a matrix (7,3)which includes between 0,1
import numpy as np
np.random.rand(7,3)

array([[0.44894103, 0.86504431, 0.85756901],
       [0.47186356, 0.20909373, 0.21096827],
       [0.01718084, 0.42482309, 0.71552374],
       [0.69011229, 0.34543642, 0.54571555],
       [0.07730069, 0.06424945, 0.63375587],
       [0.72437852, 0.52676205, 0.12467864],
       [0.13166285, 0.73808127, 0.25096614]])

In [2]:
#create a 2-D array of order(4,4)with random numbers between 0 to1
import numpy as np
np.random.rand(4,4)

array([[0.32429975, 0.02094495, 0.03557506, 0.7245281 ],
       [0.83020051, 0.55546507, 0.57094053, 0.32599233],
       [0.12004704, 0.80028162, 0.12240136, 0.61865267],
       [0.82758714, 0.64283644, 0.55999715, 0.21858837]])

**randn**

In [3]:
#it is used to generate random numbers  from normal distribution within a range


In [5]:
#generate random numbers from normal distribution 
np.random.randn(10)

array([-1.46420404,  2.63805307,  0.40038098,  2.55245213,  0.98476146,
       -1.74727764, -1.40035051,  1.22184741, -0.37918472,  0.09114452])

In [9]:
#create a 2-D array of order(5,5) which includes normal distribution values
import numpy as np
np.random.randn(5,5)

array([[ 2.220506  , -1.07639163, -0.38931153, -0.56936805,  0.9508666 ],
       [ 0.31813441,  0.52159243,  1.57522632, -0.40929076, -1.31189119],
       [-0.47965338,  1.47222464, -0.71127022, -0.33909214,  0.01825938],
       [ 0.13813664,  0.82899199, -0.98886079, -1.65885165, -0.49224279],
       [-0.11512697, -0.58721209, -1.41100436, -0.97369541, -0.11883275]])

In [12]:
#create 10 random numbers between 1 to 10000
arr=np.random.randint(1,10000,10)
print(arr)

[3155 8475 4371 4836 8748   50 7675 8816 1926 9739]


In [13]:
#maximum value
np.max(arr)

np.int32(9739)

In [18]:
#minimum value
np.min(arr)

np.int32(50)

In [19]:
#argmax it is used to get the index value of maximum value in an array
np.argmax(arr)

np.int64(9)

In [22]:
#argmin it is used to get the index value of minimum value in an array
np.argmin(arr)

np.int64(5)

**indexing**

In [28]:
A=np.arange(1,15)
print(A)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [42]:
A=np.arange(20,30)
print(A)

[20 21 22 23 24 25 26 27 28 29]


In [33]:
#fetch 24
A[4]

np.int64(24)

In [43]:
#fetch 23,24,25
A[3:6]          #note:fetch multiple values we use (:)

array([23, 24, 25])

In [45]:
#how to revers an array
A[::-1]

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20])

**indexing with 2-D array**

In [47]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
#fetch first row
arr[[0]]

array([[1, 2, 3]])

In [49]:
#fetch third row
arr[[2]]

array([[7, 8, 9]])

In [50]:
#fetch first and third row
arr[[0,2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [52]:
#fetch the first and second row
arr[[0,1]]

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
#fetch 4
arr[1][0]

np.int64(4)

In [55]:
#fetch only 8
arr[2][1]

np.int64(8)

In [56]:
#fetch 6
arr[1,2]  #note:- we are using in one square brackets also two  square brakets

np.int64(6)

In [57]:
#fetch first colum
arr[:,[0]]

array([[1],
       [4],
       [7]])

In [59]:
#fetch third colum
arr[:,[2]]

array([[3],
       [6],
       [9]])

In [61]:
#fetch first and third colum
arr[:,[0,2]]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [62]:
#fetch first and second colum
arr[:,[0,1]]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [63]:
arr1=np.array([10,20,30,40])
arr2=np.array([1,2,3,4])

In [64]:
arr1+arr2

array([11, 22, 33, 44])

In [65]:
arr1-arr2

array([ 9, 18, 27, 36])